batch_size: 256 # def: 256

# Resume Training, start from scratch or resume training
resume_train: False
load_epoch: 20

# Learning Parameters
n_epochs: 60
learning_rate: 0.01  # def:0.01
lr_policy: step  # def: step or auto
lr_adapt_threshold: 0.01
lr_step: [20, 40]  # def: 20, learning rate will be reduced by 10 times at these steps

# Data
use_data_layer: False
rand_crop: True # def: True
shuffle: False # def: False, if shuffle the batches
para_load: True

# Momentum
use_momentum : True # def: True
use_nesterov_momentum: False # def: False
momentum: 0.9 # def: 0.9

# Weight Decay
weight_decay: 0.0005 # def: 0.0005

# Directories
train_file: ../data/imagenet/train10.lmdb
test_file: ../data/imagenet/test10.lmdb
mean_file: ../data/imagenet/mean.lmdb
weights_dir: ../models/alexnet_python  # directory for saving weights and results

# conv library
lib_conv: cudaconvnet

snapshot_freq: 1  # frequency of saving weights
print_train_error: True
print_freq: 20  # frequency of printing training error rate

gpu: 'gpu0'
